global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'queue-manager'
    static_configs:
      - targets: ['queue-manager:8080']

  - job_name: 'scheduler'
    static_configs:
      - targets: ['scheduler:8080']